spring:
  jackson:
    defaultPropertyInclusion: "non_null"
  datasource:
    driverClassName: 'org.postgresql.Driver'
    url: jdbc:postgresql://localhost:5433/db
    username: postgres
    password: postgres
  jpa:
    showSql: 'true'
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
  servlet:
    multipart:
      max-file-size: 50MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    debug: true

application:
  file:
    upload:
      photos-path: ./uploads